server:
  port: 8081

spring:
  application:
    name: customer
  datasource:
    username: 'admin'
    url: jdbc:postgresql://localhost:5432/bookstore
    password: 'admin123'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: true
  profiles:
    active: default