services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: bookstore
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  kafka:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:9092"
    networks:
      - spring
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres: