apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: agarfuin/notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: mail-credentials
                  key: MAIL_HOST
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-credentials
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-credentials
                  key: MAIL_PASSWORD
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: mail-credentials
                  key: MAIL_PORT
      restartPolicy: Always
