apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_SECRET_KEY: <YOUR-BASE64-ENCODED-JWT-SECRET-KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-credentials
type: Opaque
data:
  MAIL_USERNAME: <YOUR-BASE64-ENCODED-MAIL-USERNAME>
  MAIL_PASSWORD: <YOUR-BASE64-ENCODED-MAIL-PASSWORD>
  MAIL_HOST: <YOUR-BASE64-ENCODED-MAIL-HOST>
  MAIL_PORT: <YOUR-BASE64-ENCODED-MAIL-PORT>