apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_SECRET_KEY: OWIwZjMyY2Q5NGY3ZjQ2ZmM5NTM3ZDRiMDk4YTllZDg2MThjNzk2NjQzYTI5ODIwNTEyNzU0NjU3NDZkMzY0MGU0MmVkYzg4MzAwNTMxZjBlMzUxZjVkZmZjMjI5ZjNkOGEzMGQxZTVhZDUwNDk3MDBmZjE3NWYxNjRiNThlOGI0MDI0YzBjYjdhYjNmZjM4YWNlOTQzOTk1MGE4ZjdlNDMwNWVlOTM4YzExZTE2MGM5ZmVjZjU1MTA2ZGNmNzhhZjM4YjA4YWJjY2Y2ODRjMjg4NmU4YTdhNDJlMjgyZDk2N2ZmODkzMmVkMzlhYmMzMjkwYTE5MmY4ZTU4ZjQzMWJmYTcxNTI1ODMwNGVhMDI4Y2EwOWRmYzRiNzQwYjY2ZDAyMjlkM2JjOWM5YWM3MGY5MzRjNjFhZjI5N2QwMmI2MDA3NGRiZTAyZWE4OTIwZTIyODAzODUxZTBkNWEwNDUyMDdjYjU4YjFjYjU2NTdiNzAwMTUwYzEzMjQ2YjBlMzUxYTQ4ZGU0MThlYjg5M2UxNDVmY2QxYmNiOWVhMjk4YWU2YWM1NTcwZDhiN2YxYWJhOWZiYjEzZTA3NDI0OTRjMzk5OTBiODBiMzRlZDVlNDRjZjA3N2Q2NWQ5ZWY2YjczZDllYzM1M2Q1MjJlNmE1M2IyYTRiOTIyYTMzMTc=
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-credentials
type: Opaque
data:
  MAIL_USERNAME: aGFydW5zZWxtYW5rYXJha2FzQGdtYWlsLmNvbQ==
  MAIL_PASSWORD: YmpwZnB0cnljbmNmeHd0Zw==
  MAIL_HOST: c210cC5nbWFpbC5jb20=
  MAIL_PORT: NTg3
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW4xMjM=
  POSTGRES_DB: Ym9va3N0b3Jl
